<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugPackage</Configurations>
    <VersionPrefix>1.0.2</VersionPrefix>
	<VersionSuffix></VersionSuffix>
	<BaseOutputPath></BaseOutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

	<PropertyGroup>
		<EnablePostBuildCopy Condition="'$(EnablePostBuildCopy)' == ''">true</EnablePostBuildCopy>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Link="README.md" CopyToPublishDirectory="Always" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="GitVersion.MsBuild" Version="6.5.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Serilog" Version="4.0.1" />
	  <PackageReference Include="Syncfusion.Licensing" Version="27.2.2" />
	  <PackageReference Include="System.Management" Version="10.0.3" />
	</ItemGroup>
</Project>
