<Project Sdk="Microsoft.NET.Sdk">

  <Target Name="SetVersionFromGit" BeforeTargets="GetAssemblyVersion;GenerateNuspec" Condition=" '$(OS)' == 'Windows_NT' ">
    <Exec Command="git describe --tags" ConsoleToMSBuild="true" IgnoreExitCode="false">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitDescribe" />
    </Exec>
    <PropertyGroup>
      <!-- Extracts '1.2.10' from 'v1.2-10-g01ee017' -->
      <Version>$([System.Text.RegularExpressions.Regex]::Match($(GitDescribe), `^v?(\d+\.\d+)-(\d+)-.*$`).Groups[1].Value).$([System.Text.RegularExpressions.Regex]::Match($(GitDescribe), `^v?(\d+\.\d+)-(\d+)-.*$`).Groups[2].Value)</Version>
      <PackageVersion>$(Version)</PackageVersion>
    </PropertyGroup>
    <Message Text="Setting version to $(Version) based on 'git describe'" Importance="high" />
  </Target>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>C:\Users\csdel\source\MyLocalNuget\</PackageOutputPath>
  </PropertyGroup>

	<PropertyGroup>
		<EnablePostBuildCopy Condition="'$(EnablePostBuildCopy)' == ''">true</EnablePostBuildCopy>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="GitVersion.MsBuild" Version="6.5.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Serilog" Version="4.0.1" />
	  <PackageReference Include="System.Management" Version="9.0.0" />
	</ItemGroup>

</Project>
