<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

	<PropertyGroup>
		<EnablePostBuildCopy Condition="'$(EnablePostBuildCopy)' == ''">true</EnablePostBuildCopy>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(EnablePostBuildCopy)' == 'true' And '$(OS)' == 'Windows_NT' ">
		<Exec Command="xcopy /Y /D &quot;$(TargetDir)$(AssemblyName).dll&quot; &quot;$(SolutionDir)\..\..\output\&quot;" />
	</Target>

	<ItemGroup>
	  <PackageReference Include="GitVersion.MsBuild" Version="6.5.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Serilog" Version="4.0.1" />
	  <PackageReference Include="System.Management" Version="9.0.0" />
	</ItemGroup>

	<Target Name="PackAndDeployToLocalFeed" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">

		<Message Text="--- PackAndDeployToLocalFeed TARGET IS RUNNING (using dotnet pack) ---" Importance="high" />

		<Exec Command="dotnet pack &quot;$(MSBuildProjectFullPath)&quot; --configuration $(Configuration) --no-build --output &quot;C:\Users\csdel\source\MyLocalNuget\&quot;" />

		<Message Text="--- PackAndDeployToLocalFeed TARGET FINISHED ---" Importance="high" />
	</Target>

</Project>
